### PR TITLE
daemon: Remove timer that waits for the suspend operation to finish

### LINKED ISSUE #609: SSH timeout error on `suspend`
Suspending an instance took longer than usual (`iowait` likely) and multipass threw an error out:
```
$ multipass suspend snapcraft-multipass                 
suspend failed: [ssh proc] failed to open session channel: '' 
```

### PR DESCRIPTION
**Pull request by townsend2010**
The EventLoop tied to the QTimer was causing unintended behavior.  Instead, just wait
on suspend to finish in the particular backend code.

Fixes #609

### CODE REVIEW

File: src/daemon/daemon.cpp [hunk 1]
```diff
@@ -1778,7 +1768,6 @@ void mp::Daemon::on_stop()
 
 void mp::Daemon::on_suspend()
```
Comment (ricab) [inline src/daemon/daemon.cpp]: I suppose this override could be removed from the daemon entirely?

File: src/daemon/daemon.cpp [hunk 2]
```diff
@@ -1563,18 +1563,8 @@ try // clang-format on
 
         for (const auto& name : instances_to_suspend)
```
Comment (ricab) [inline src/daemon/daemon.cpp]: Might as well replace the loop with a call to cmd_vms...

File: src/daemon/daemon.h [hunk 3]
```diff
@@ -123,9 +123,6 @@ public slots:
     grpc::Status version(grpc::ServerContext* context, const VersionRequest* request,
                          grpc::ServerWriter<VersionReply>* response) override;
 
-signals:
```
Comment (ricab) [inline src/daemon/daemon.h]: Question: isn't there a corresponding connect call to remove too?

File: src/platform/backends/qemu/qemu_virtual_machine.cpp [hunk 4]
```diff
@@ -370,6 +370,7 @@ void mp::QemuVirtualMachine::suspend()
             update_state();
 
             update_shutdown_status = false;
+            vm_process->waitForFinished();
```
Comment (ricab) [inline src/platform/backends/qemu/qemu_virtual_machine.cpp]: No parallel in other backends?

File: src/daemon/daemon.cpp (hunk 1 above)
Comment (townsend2010) [reply src/daemon/daemon.cpp]: It could, but I think that is out of scope for this PR.  The other `on_foo()` methods are the same as well.

File: src/daemon/daemon.h (hunk 3 above)
Comment (townsend2010) [reply src/daemon/daemon.h]: Yes, and it has been removed in line 1569 in daemon.cpp above.

File: src/platform/backends/qemu/qemu_virtual_machine.cpp (hunk 4 above)
Comment (townsend2010) [reply src/platform/backends/qemu/qemu_virtual_machine.cpp]: Not the `libvirt` backend since all operations go through `libvirtd`, there is really nothing to wait on.

File: src/daemon/daemon.cpp (hunk 2 above)
Comment (townsend2010) [reply src/daemon/daemon.cpp]: Sure, this is a good candidate to switch over to that.

File: src/daemon/daemon.cpp (hunk 1 above)
Comment (ricab) [reply src/daemon/daemon.cpp]: I understand what you say in regard to the other dangling `on_foo` methods, but this one *becomes* dangling in this PR if not removed. Personally I would have nothing against cleaning other `on_foo` methods here (that is justified by consistency with other PR changes IMO), but that's a separate question.

File: src/daemon/daemon.h (hunk 3 above)
Comment (ricab) [reply src/daemon/daemon.h]: Ah sorry I overlooked that

File: src/platform/backends/qemu/qemu_virtual_machine.cpp (hunk 4 above)
Comment (ricab) [reply src/platform/backends/qemu/qemu_virtual_machine.cpp]: Ack

File: src/daemon/daemon.cpp (hunk 1 above)
Comment (townsend2010) [reply src/daemon/daemon.cpp]: I understand what you are saying about it becoming dangling, but I'm not keen on messing with the VMStatusMonitor class with this PR.

File: src/daemon/daemon.cpp (hunk 2 above)
Comment (townsend2010) [reply src/daemon/daemon.cpp]: Ok, I updated this to use `cmd_vms()`.

**Comment by townsend2010** [comment]
bors r=ricab

**Comment by townsend2010** [comment]
bors r=ricab

**Comment by townsend2010** [comment]
bors r=ricab
