### PR TITLE
sftpserver: Support extended SFTP methods

### LINKED ISSUE #144: Function not implemented error on os.link call
Snapping `demos/opencv` from the Snapcraft source tree which is mounted into the instance via `multipass mount` fails while staging the "example" part. It seems like hard linking doesn't work.

> Staging example 
> Traceback (most recent call last):
>   File "/home/ubuntu/dev/snapcraft/snapcraft/file_utils.py", line 166, in link_or_copy
>     os.link(source_path, destination, follow_symlinks=False)
> OSError: [Errno 38] Function not implemented: '/home/ubuntu/dev/snapcraft/demos/opencv/parts/example/install/usr/share/doc/libdrm-nouveau2/changelog.Debian.gz' -> '/home/ubuntu/dev/snapcraft/demos/opencv/stage/usr/share/doc/libdrm-nouveau2/changelog.Debian.gz'
> [...]
>   File "/usr/lib/python3.5/shutil.py", line 251, in copy2
>     copyfile(src, dst, follow_symlinks=follow_symlinks)
>   File "/usr/lib/python3.5/shutil.py", line 112, in copyfile
>     os.symlink(os.readlink(src), dst)
> FileNotFoundError: [Errno 2] No such file or directory: '../libdrm2/changelog.Debian.gz' -> '/home/ubuntu/dev/snapcraft/demos/opencv/stage/usr/share/doc/libdrm-nouveau2/changelog.Debian.gz'

### PR DESCRIPTION
**Pull request by townsend2010**
Support the "hardlink@openssh.com" and "posix-rename@openssh.com" extended methods.
Fixes #144

### CODE REVIEW

File: tests/mock_sftpserver.cpp [hunk 1]
```diff
@@ -30,6 +30,7 @@ extern "C"
     IMPL_MOCK_DEFAULT(2, sftp_reply_handle);
     IMPL_MOCK_DEFAULT(1, sftp_get_client_message);
     IMPL_MOCK_DEFAULT(1, sftp_client_message_free);
+    IMPL_MOCK_DEFAULT(1, sftp_client_message_get_submessage);
```
Comment (albaguirre) [inline tests/mock_sftpserver.cpp]: Looks like this is not needed based on the tests. 

If it's needed in the future, it also needs to be added to "c_mock_defines.cmake"

File: src/sshfs_mount/sftp_server.cpp [hunk 2]
```diff
@@ -687,3 +690,30 @@ int mp::SftpServer::handle_write(sftp_client_message msg)
...
+        if (!mp::platform::link(old_name, new_name))
+            return reply_failure(msg);
+    }
+    else if (method == "posix-rename@openssh.com")
+    {
+        return handle_rename(msg);
+    }
+    else
+    {
+        return reply_failure(msg);
```
Comment (albaguirre) [inline src/sshfs_mount/sftp_server.cpp]: Should this be SSH_FX_OP_UNSUPPORTED instead?

Also this path is missing a test, perhaps something like:

```
    auto sftp = make_sftpserver();

    auto msg = make_msg(SFTP_EXTENDED);
    auto submessage = name_as_char_array("invalid submessage");
    msg->submessage = submessage.data();

    REPLACE(sftp_get_client_message, make_msg_handler());

    int num_calls{0};
    auto reply_status = make_reply_status(msg.get(), SSH_FX_OP_UNSUPPORTED, num_calls);

    REPLACE(sftp_reply_status, reply_status);

    sftp.run();

    EXPECT_THAT(num_calls, Eq(1));
```

File: tests/mock_sftpserver.h [hunk 3]
```diff
@@ -35,6 +35,7 @@ DECL_MOCK(sftp_reply_names_add);
 DECL_MOCK(sftp_reply_handle);
 DECL_MOCK(sftp_get_client_message);
 DECL_MOCK(sftp_client_message_free);
+DECL_MOCK(sftp_client_message_get_submessage);
```
Comment (albaguirre) [inline tests/mock_sftpserver.h]: Looks like this is not needed based on the tests.

If it's needed in the future, it also needs to be added to "c_mock_defines.cmake"

File: tests/test_sftpserver.cpp [hunk 4]
```diff
@@ -802,6 +804,68 @@ TEST_F(SftpServer, handles_reads)
...
+{
+    mpt::TempDir temp_dir;
+    auto file_name = temp_dir.path() + "/test-file";
+    auto link_name = temp_dir.path() + "/test-link";
+    make_file_with_content(file_name);
+
+    auto sftp = make_sftpserver();
+    auto msg = make_msg(SFTP_EXTENDED);
+    std::string extended_method("hardlink@openssh.com");
+    auto submessage = name_as_char_array(extended_method);
```
Comment (albaguirre) [inline tests/test_sftpserver.cpp]: This could just be auto submessage = name_as_char_array("hardlink@openssh.com");

File: tests/test_sftpserver.cpp [hunk 5]
```diff
@@ -802,6 +804,68 @@ TEST_F(SftpServer, handles_reads)
...
+{
+    mpt::TempDir temp_dir;
+    auto old_name = temp_dir.path() + "/test-file";
+    auto new_name = temp_dir.path() + "/test-renamed";
+    make_file_with_content(old_name);
+
+    auto sftp = make_sftpserver();
+    auto msg = make_msg(SFTP_EXTENDED);
+    std::string extended_method("posix-rename@openssh.com");
+    auto submessage = name_as_char_array(extended_method);
```
Comment (albaguirre) [inline tests/test_sftpserver.cpp]: This could just be auto submessage = name_as_char_array("posix-rename@openssh.com");

**Comment by townsend2010** [comment]
Thanks!  Updated with requested changes:)
