### PR TITLE
ssh_process: Return any data already read if the channel is closed

### LINKED ISSUE #425: mount on startup sometimes fail due to the instance not being ready yet
While we've increased the timeout for some commands, it seems we've missed some, especially around mounting:

```
$ SNAPCRAFT_BUILD_INFO=1 SNAPCRAFT_BUILD_ENVIRONMENT=multipass snapcraft
Launching a VM.
start failed: The following errors occurred:                                    
Removing "/home/multipass/project": stoi
An error occurred when trying to start the instance with 'multipass': returned exit code 2.
Ensure that 'multipass' is setup correctly and try again.
```

### PR DESCRIPTION
**Pull request by townsend2010**
Also add more verbose debugging info for catching cases like this in the future.

Fixes #425

Co-authored-by: Chris Townsend <christopher.townsend@canonical.com>

### CODE REVIEW

File: src/ssh/ssh_process.cpp [hunk 1]
```diff
@@ -116,17 +128,25 @@ std::string mp::SSHProcess::read_stream(StreamType type, int timeout)
...
+                return output.str();
+            }
 
             throw std::runtime_error(fmt::format("error while reading ssh channel for remote process '{}'"
                                                  " - error: {}",
                                                  cmd, num_bytes));
         }
         output.write(buffer.data(), num_bytes);
+        mpl::log(mpl::Level::debug, category,
+                 fmt::format("{}:{} {}(): output = {}", __FILE__, __LINE__, __FUNCTION__, output.str()));
```
Comment (Saviq) [inline src/ssh/ssh_process.cpp]: I'm worried this might be too much, imagine a long-running command through this, do we want to log that much?

Comment (townsend2010) [reply src/ssh/ssh_process.cpp]: Yeah, probably too verbose right here.  I'll take that out.
