### PR TITLE
delayed_shutdown: Catch thrown exception if ssh exec fails

### LINKED ISSUE #1128: Core dump purging instance, uncaught "std::runtime_error"
Issued `halt` in a machine in "Delayed Shutdown" state, then `multipass stop --all` because it didn't register with `multipassd`, it dumped on me:
```
paź 19 11:43:26 michal-laptop multipassd[16150]: shutdown request delayed for 10 minutes
paź 19 11:45:47 michal-laptop multipassd[16150]: qmp: {"timestamp": {"seconds": 1571478347, "microseconds": 622777}, "event": "rtc_change", "data": {"offset": 1}}
paź 19 11:46:45 michal-laptop multipass.multipassd[16150]: terminate called after throwing an instance of 'std::runtime_error'
paź 19 11:46:45 michal-laptop multipass.multipassd[16150]:   what():  [ssh proc] failed to open session channel: 'socket error: disconnected'
paź 19 11:46:45 michal-laptop systemd[1]: snap.multipass.multipassd.service: main process exited, code=dumped, status=6/abrt
paź 19 11:47:16 michal-laptop systemd[1]: snap.multipass.multipassd.service: state 'stop-sigterm' timed out. killing.
paź 19 11:47:16 michal-laptop systemd[1]: snap.multipass.multipassd.service: killing process 16586 (dnsmasq) with signal sigkill.
paź 19 11:47:16 michal-laptop systemd[1]: snap.multipass.multipassd.service: killing process 28213 (qemu-system-x86) with signal sigkill.
paź 19 11:47:16 michal-laptop systemd[1]: snap.multipass.multipassd.service: failed with result 'core-dump'.
paź 19 11:47:16 michal-laptop systemd[1]: snap.multipass.multipassd.service: service restartsec=100ms expired, scheduling restart.
paź 19 11:47:16 michal-laptop systemd[1]: snap.multipass.multipassd.service: scheduled restart job, restart counter is at 1.
paź 19 11:47:16 michal-laptop systemd[1]: Stopped Service for snap application multipass.multipassd.
```

### PR DESCRIPTION
**Pull request by townsend2010**
Fixes #1128

### CODE REVIEW

File: src/daemon/delayed_shutdown_timer.cpp [hunk 1]
```diff
@@ -55,13 +55,22 @@ mp::DelayedShutdownTimer::~DelayedShutdownTimer()
...
-            ssh_session->exec("wall The system shutdown has been cancelled").exit_code();
+            if (ssh_session)
+            {
+                // exit_code() is here to make sure the command finishes before continuing in the dtor
+                ssh_session->exec("wall The system shutdown has been cancelled").exit_code();
+            }
+            mpl::log(mpl::Level::info, virtual_machine->vm_name, fmt::format("Cancelling delayed shutdown"));
+            virtual_machine->state = VirtualMachine::State::running;
+        }
+        catch (const std::exception& e)
```
Comment (ricab) [inline src/daemon/delayed_shutdown_timer.cpp]: Yup! You almost got me there  :smirk: I was about to complain and then realized this is a dtor, so a boundary where no exception should pass. Good call.
