### PR TITLE
url_downloader: Directly use network cache when downloading data

### LINKED ISSUE #825: Image hashes may not match when a new cloud-image is uploaded
We ran into a situation where new minimal cloud images were uploaded, but we were getting image hash mismatch errors.

Turns out that the SHA256SUM file is cached by Qt and it was using an older cached version of that file instead or retrieving the new one. 

We need to force Qt to always hit the actual URL when retrieving the hash file.

### LINKED ISSUE #829: `multipass launch…` should work offline for all cached images
Today when the daemon is started with no network, the daemon just decides there's no images:

```
$ multipass find
No images found.
$ multipass launch 
launch failed: Remote "" is unknown or unreachable. 
```

We should cache at least enough of the image metadata along with the images to make this work.

### PR DESCRIPTION
**Pull request by townsend2010**
Due to how QNetwork handles caching via QNetworkAccessManager and issues it
causes, instead directly access the network cache. This includes comparing the
Last-Modified header of the URL to what is cached and also use cached data (if
availble) when there is an issue downloading the data from the URL.

Fixes #825, fixes #829

### CODE REVIEW

**Comment by Saviq** [comment]
Hey, could we have tests for this?

**Comment by townsend2010** [comment]
@Saviq,

I thought about it and we would need to mock things like `QNetworkDiskManager` and be able to populate it with cache data in a way that works for `QAbstractNetworkCache`.  I didn't see any straightforward way to do that, although thinking about it as I write this, I wonder if it's possible to do something with our premock stuff we use for testing.  I'll look into that before declaring that this would take too much time for a small gain.

**Comment by townsend2010** [comment]
Ok doesn't look like premock will help us on this.  So basically, what would need to be done is pre-populate a cache that is understood by `QNetworkDiskCache`.  This would be fragile since in the Qt code, they use internal versioning of the cache and use obscure file names along with internal metadata in the cache files we'd have to get correct.

I can add this basing this on the real cache on my system, but it could be prone to breakage down the line if Qt decides to change how it handles the cache internally, including path versioning that it uses and special metadata in the cache file.  I'm just not sure it's worth it.

**Comment by townsend2010** [comment]
After some more looking at this, I really don't think it's worth the effort to put in the static caching infrastructure (which would potentially be fragile to Qt changes) in place for testing this small chunk of code.

File: src/network/url_downloader.cpp [hunk 1]
```diff
@@ -149,11 +158,53 @@ QByteArray mp::URLDownloader::download(const QUrl& url)
...
+        QDateTime modified;
+
+        try
+        {
+            modified = last_modified(url);
+        }
+        catch (const std::exception& e)
+        {
+            // Force using the cached data if the URL is unreachable
+            modified = metadata.lastModified();
```
Comment (gerboland) [inline src/network/url_downloader.cpp]: Could you not just do

    return get_network_cache_data(network_cache, url);

from here instead of setting `modified` to a value that makes the later if() true, that calls the above anyway?

Comment (townsend2010) [reply src/network/url_downloader.cpp]: @gerboland,

Thanks for the review.  It is difficult to test and that is how I tested it too.

Sure, I can change that and it would make it more clear.

Comment (townsend2010) [reply src/network/url_downloader.cpp]: Ok, i tightened up this code.  Thanks!

**Comment by townsend2010** [comment]
Shall we merge?

**Comment by gerboland** [comment]
Nobody else has opinion then? Ok, then
bors r+

**Comment by Saviq** [comment]
Well, I *do* have an opinion.

~~Everything~~This is awesome!
