### PR TITLE
downloader: Reset timer when readReady is emitted for general downloads

### LINKED ISSUE #386: Network timeout too aggressive
If my network is not at its best state with regards to latency, it is rather easy to get:
```
$ multipass launch
failed to launch: Network timeout                                               
$ multipass launch                        
failed to launch: Network timeout
```

As a side data point, using snapcraft or having lxd auto trigger the new image download does not timeout like this. I have not timed it, but feels like it waits only 2 seconds to decide on a timeout.

### PR DESCRIPTION
**Pull request by townsend2010**
Fixes #386

### CODE REVIEW

File: src/network/url_downloader.cpp [hunk 1]
```diff
@@ -128,8 +129,11 @@ void mp::URLDownloader::download_to(const QUrl& url, const QString& file_name, i
 
 QByteArray mp::URLDownloader::download(const QUrl& url)
 {
-    return ::download(manager, timeout, url, [](QNetworkReply*, qint64, qint64) {}, [](QNetworkReply*, QTimer&) {},
-                      [] {});
+    // This will connect to the QNetworkReply::readReady signal and when emitted,
+    // reset the timer.
+    auto on_download = [](QNetworkReply* reply, QTimer& download_timeout) { download_timeout.start(); };
```
Comment (ricab) [inline src/network/url_downloader.cpp]: Why are lines 111-114 needed there but not here?

Comment (townsend2010) [reply src/network/url_downloader.cpp]: @ricab, Because in lines 111-114, we want to stop the timer to allow time reading from the `QNetworkReply` and write to the file.  Here, we are not doing that and calling `start()` just resets the timer.

Comment (ricab) [reply src/network/url_downloader.cpp]: @townsend2010 OK thanks, I missed that and thought could be part of the resetting

**Comment by ricab** [comment]
bors delegate=townsend2010

**Comment by townsend2010** [comment]
bors r=ricab
