### PR TITLE
backend/libvirt: Fix not detecting new instance state

### LINKED ISSUE #993: [libvirt] fails to notice instance is already running
```
$ virsh list
 Id   Name                   State
--------------------------------------
 5    snapcraft-subsurface   running

$ multipass ls                       
Name                    State             IPv4             Image
snapcraft-subsurface    Stopped           --               Ubuntu Snapcraft builder for Core 18

$ multipass start snapcraft-subsurface
start failed: Requested operation is not valid: domain is already running
```

### PR DESCRIPTION
**Pull request by townsend2010**
Better detect when an instance is started/stopped outside of Multipass.

Fixes #993

### CODE REVIEW

File: src/platform/backends/libvirt/libvirt_virtual_machine.cpp [hunk 1]
```diff
@@ -199,22 +199,33 @@ auto domain_by_definition_for(const mp::VirtualMachineDescription& desc, const s
...
-    {
-        return mp::VirtualMachine::State::unknown;
-    }
+    if (domain_state == VIR_DOMAIN_SHUTOFF)
+        return mp::VirtualMachine::State::off;
+
+    if (domain_state == VIR_DOMAIN_RUNNING && current_instance_state == mp::VirtualMachine::State::off)
+        return mp::VirtualMachine::State::running;
+
+    return current_instance_state;
```
Comment (gerboland) [inline src/platform/backends/libvirt/libvirt_virtual_machine.cpp]: Why are you passing Multipass' thinking of the current state through? Can we not read all possible states directly from libvirt?

File: src/platform/backends/libvirt/libvirt_virtual_machine.cpp [hunk 2]
```diff
@@ -199,22 +199,33 @@ auto domain_by_definition_for(const mp::VirtualMachineDescription& desc, const s
...
         return mp::VirtualMachine::State::unknown;
 
     if (virDomainHasManagedSaveImage(domain, 0) == 1)
         return mp::VirtualMachine::State::suspended;
 
-    if (virDomainGetState(domain, &state, nullptr, 0) == -1)
-    {
-        return mp::VirtualMachine::State::unknown;
-    }
+    if (domain_state == VIR_DOMAIN_SHUTOFF)
```
Comment (gerboland) [inline src/platform/backends/libvirt/libvirt_virtual_machine.cpp]: Why don't you deal with the other possible states like SHUTDOWN, CRASHED, PAUSED & BLOCKED?

File: src/platform/backends/libvirt/libvirt_virtual_machine.cpp [hunk 3]
```diff
@@ -380,17 +388,14 @@ void mp::LibVirtVirtualMachine::ensure_vm_is_running()
...
     {
         // Have to set 'off' here so there is an actual state change to compare to for
         // the cond var's predicate
         state = State::off;
         state_wait.notify_all();
-        if (present_state == VirtualMachine::State::unknown)
-            throw mp::StartException(vm_name, "Unable to determine state");
 
-        throw mp::StartException(vm_name, "Instance shutdown during start");
+        throw mp::StartException(vm_name, "Instance shut down while starting");
```
Comment (gerboland) [inline src/platform/backends/libvirt/libvirt_virtual_machine.cpp]: I dunno, maybe "failed to start" ? Since a crash would result in this too, no?

File: src/platform/backends/libvirt/libvirt_virtual_machine.cpp (hunk 1 above)
Comment (townsend2010) [reply src/platform/backends/libvirt/libvirt_virtual_machine.cpp]: There are a number of Multipass states that have no analogous `libvirt` states such as `DELAYED_SHUTDOWN`, `STARTING`, `SUSPENDING`, and Multipass's way of handling `UNKNOWN`. So in this particular piece of code, this is the "fallthrough" in which we just return what Multipass has stored since no libvirt state matches.

File: src/platform/backends/libvirt/libvirt_virtual_machine.cpp (hunk 2 above)
Comment (townsend2010) [reply src/platform/backends/libvirt/libvirt_virtual_machine.cpp]: I suppose I should account for those libvirt states as well.  I'll add them.

File: src/platform/backends/libvirt/libvirt_virtual_machine.cpp (hunk 3 above)
Comment (townsend2010) [reply src/platform/backends/libvirt/libvirt_virtual_machine.cpp]: Yeah, I suppose being more generic here will be better.

**Comment by townsend2010** [comment]
> And can this fix get a test?

I'll think about how best to go about adding a test that mimics the bug's behavior.  I will say, this PR adds a significant amount more coverage, so the current tests actually test some of this.

File: src/platform/backends/libvirt/libvirt_virtual_machine.cpp (hunk 2 above)
Comment (townsend2010) [reply src/platform/backends/libvirt/libvirt_virtual_machine.cpp]: Ok, I have accounted for all of the domain states and basically set them to `off` for the returned instance state.

File: src/platform/backends/libvirt/libvirt_virtual_machine.cpp (hunk 3 above)
Comment (townsend2010) [reply src/platform/backends/libvirt/libvirt_virtual_machine.cpp]: Done

**Comment by townsend2010** [comment]
>> And can this fix get a test?

>I'll think about how best to go about adding a test that mimics the bug's behavior. I will say, this PR adds a significant amount more coverage, so the current tests actually test some of this.

Ok, I added a test that should mimic the behavior that caused #993.

File: src/platform/backends/libvirt/libvirt_virtual_machine.cpp (hunk 1 above)
Comment (gerboland) [reply src/platform/backends/libvirt/libvirt_virtual_machine.cpp]: I see. Could I request a function name change of `domain_state_for` to something like `resolve_domain_state_with_current` ?

**Comment by gerboland** [comment]
Thanks for the improvements & test. I've one niggle, but am otherwise happy

File: src/platform/backends/libvirt/libvirt_virtual_machine.cpp (hunk 1 above)
Comment (townsend2010) [reply src/platform/backends/libvirt/libvirt_virtual_machine.cpp]: I kept thinking the function name morphed into a weak name, and as we all know, naming functions (and variables) is one of the hardest software engineering principles :grinning:, I was drawing a blank on what to rename it.  I'll change it for sure.

Comment (townsend2010) [reply src/platform/backends/libvirt/libvirt_virtual_machine.cpp]: Ok, I renamed it.  Let me know what you think.
